### ISSUE TITLE
Not possible to compile SerialToWifi under ESP32 V1.6.00

### ISSUE THREAD

**Issue by pberna67** [Invzblio/SerialToWifi#1]
Dear Developer

I'm trying  to compile the attached sketch with SerialToWifi integration under ESP32 v1.0.6 but I seeing the following compiler errors:

Multiple libraries were found for "WiFiClient.h"
In file included from C:\Users\pabe\Documents\Arduino\MyExamples\MySimpleMQTT\TemperatureMonitor8MQTTClient_GitHub\TemperatureMonitor8MQTTClient_GitHub.ino:16:0:
 Used: C:\Users\pabe\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi
C:\Users\pabe\Documents\Arduino\libraries\SerialToWifi\src/SerialToWifi.h:6:25: fatal error: TimeLib.h: No such file or directory
 Not used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.51.0_x86__mdqgnx93n4wtt\libraries\WiFi
compilation terminated.
exit status 1
Error compiling for board u-blox NINA-W10 series (ESP32).
 SerialToWifi using ESP 32 platform V1.0

**How to reproduce: just compile the attached sketch using Arduino IDE 1.8.16 and SerialToWifi lib : 0.1.4 and the below additional library installed**

[TemperatureMonitor8MQTTClient_GitHub.zip](https://github.com/Invzblio/SerialToWifi/files/7382563/TemperatureMonitor8MQTTClient_GitHub.zip)

**Other data** 

**SerialToWifi lib : 0.1.4**
Board: u.blox NINA B102 board with ESP32
Core Installation/update date: ESP 32 lib available in this site today
IDE name: **Arduino IDE 1.8.16**
Flash Frequency: https://www.u-blox.com/en/product/evk-nina-w10
PSRAM enabled: unnknown
Upload Speed: 115200
Computer OS: Windows 10

**Additional not standard Libraries installed:**
SD v1.2.4
Wifi v.2.4
Dellas T%emperature v2.9.0
DS18B29 v1.0.0
ESP32TimerInterrupt v1.4.0
ESOMQTTClient v1.11.1
OneWire v2.3.5
PubSubLinbet v2.8.9
RTCLib v1.14.1
uRTCLib v6.4.0
SerialToWifi lib : 0.1.4

**Suggestion/request.: Add the possibility to log the serial data communication even in a SD/MMC attached to the board**

**Comment by Invzblio** [comment]
Hi,
Sorry for the delay in response.
It seems there is a version conflict since compiler tries to find the TimeLib.h file that was used in SerialToWifi 0.1.3. 
Version 0.1.4 does not include it. 
You might want to check if you made a local copy of 0.1.3 or if 0.1.4 is really the one installed by checking the manage libraries option. 

Hope this helps

Pascal

**Comment by pberna67** [comment]
I confirm that the the used version of your lib is the 0.1.4. However I'm seeing that you have published the 0.1.6 version. With this version the code can be compiled without error, but with 0.1.4 the error is still present
